
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

jwt.secret=MySuperSecretKeyForJWTGenerationThatIsAtLeast32CharactersLong
jwt.expirationMs=86400000

logging.level.org.example.itkissues=INFO
logging.level.org.springframework.security=INFO

logging.file.name=logs/application.log
logging.file.path=./

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

server.port=8443
server.ssl.key-store=classpath:myapp.p12
server.ssl.key-store-password=somepassword
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp