DROP TABLE IF EXISTS user_table;

CREATE TABLE IF NOT EXISTS user_table (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          username VARCHAR(50) NOT NULL UNIQUE,
                                          password VARCHAR(255) NOT NULL,
                                          role VARCHAR(20) NOT NULL,
                                          is_account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
                                          failed_login_attempts INT NOT NULL DEFAULT 0
);