server:
  port: 8083

kafka:
  bootstrap-servers: localhost:9092
  topics:
    sent-orders: sent_orders

logging:
  file:
    name: /app/logs/notifications.log
    path: /app/logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO